#!/usr/bin/python
# -*- coding: UTF-8 -*-

import warnings
warnings.filterwarnings("ignore")
import os

channel_info = os.listdir('/opt/starview/cdn/hls/bin/mdb')
#channel_info.remove('channel.db')
#channel_info.remove('vod.db')
channel = [n[:-3] for n in channel_info if n.startswith("TV")]

def live():

    tv_list = ['{"{#CHNAME}":"'+n+'"}' for n in channel]
    tv_ch = str(tv_list).replace("'","")
    json = '{"data":'+tv_ch+'}'
    return json

def hls():
    file = open('/mediadisk/hls/live/hls.txt')
    tv_list = []
    for line in file.readlines():
        line='{"{#CHNAME}":"'+line.strip('\n')+'"}'
        tv_list.append(line)

    tv_ch = str(tv_list).replace("'","")
    json = '{"data":'+tv_ch+'}'
    return json
if channel:

    if os.path.exists('/mediadisk/hls/live/hls.txt'):
        print hls() 
    else:
        print live()
else:
    print '{"data":[{"{#CHNAME}":""}]}'
